# Generated by Django 2.2 on 2020-12-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200, verbose_name='Member Username')),
                ('JoinDate', models.DateTimeField(auto_now_add=True, verbose_name='joinDate')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.DateTimeField(auto_now_add=True)),
                ('group Name', models.CharField(max_length=200, unique=True, verbose_name='group Name')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Member')),
            ],
        ),
    ]
