# Generated by Django 2.2 on 2021-01-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210101_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group Name',
            new_name='name',
        ),
    ]
